### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by raptor7197** [haturatu/ViMusic#1] opened 2024-10-18 06:35 UTC
### Feature description

is it possible to change the language of the app  in the settings menu and the favourites and the offline tabs are also showing in japanese can you provide a solution to this as i am not from a japanese speaking country.

### Why do you want this feature?

problems readiing the settings menu

**Comment by haturatu** [comment] 2024-10-18 09:17
@raptor7197 Hi, Vamsi Krishna!
I do think it is necessary. What country are you from? Your name seems to be Telugu, so are you from India?

Also, there is an issue where some of the songs in the history/cache are not playing, so I need to commit to resolving this as well.

**Comment by raptor7197** [comment] 2024-10-18 10:16
Yes, I am indeed from India.
 
Tried out your version just now apart from the language there is a slight delay in the song being searched and the results appearing when compared to the original VImusic app .

I am also working to sort out the language issue .
Will see the problem in cache.

**Comment by haturatu** [comment] 2024-10-18 10:55
oh really? the original Vimusic had issues, and I fixed them with this commit, so it shouldn't have been working. If it's slow, this is likely the issue, but it shouldn't have been working in the first place.

https://github.com/haturatu/ViMusic/commit/7781f93f951f74a17df063255fba6494b90acca7

And how many languages in India would need to be supported to cover everything?

**Comment by raptor7197** [comment] 2024-10-18 11:33
There are many languages in India (23) supporting all of them would be very exhausting .
Just the option of English would good.

**Comment by raptor7197** [comment] 2024-10-19 15:24
there is a widely spoken language but it is not compulsary for everyone in india to learn 
it's Hindi but english too is used.

**Comment by haturatu** [comment] 2024-10-20 15:37
ah, okay.
It seems that playback issues are still occurring, and I've confirmed that they happen not only with cached playback. It appears that visitorData is likely the cause, so I'll check the fixes made in a similar fork, NewPipe, and apply them to this.

I'm currently working on a separate Deno task, so it might take some time, but I'll give it a try.

**Closed** 2024-11-03 05:44 UTC
Labels: enhancement
